#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
stty -ixon
ttyctl -f

# Report time statistics for progs that take more than 10 secs to run
REPORTTIME=10

# Report any login/logout of other users
WATCH=notme
WATCHFMT='%n %a %l from %m at %T.'

# Rehash everytime, to take care of newly installed applications
zstyle ':completion:*' rehash true


# My modules
for file in ~/.zmodules/*; do
  source $file
done; unset file

# Make man pages look better with solarized
export LESS_TERMCAP_md=$'\E[0;33m' # begin bold
export LESS_TERMCAP_so=$'\E[1;30;43m' # begin standout-mode - info box
export LESS_TERMCAP_us=$'\E[4;32m' # begin underline
