#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Rehash everytime, to take care of newly installed applications
zstyle ':completion:*' rehash true

# Add my scripts to the path
path+=~/bin

# My aliases
for file in ~/.zalias/*; do
  source $file
done

# Auto ls
#function chpwd() {
    #emulate -L zsh
    #ls
#}
