#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
stty -ixon

# Rehash everytime, to take care of newly installed applications
zstyle ':completion:*' rehash true

# Add my scripts to the path
path=(~/bin $path)

# My aliases
for file in ~/.zalias/*; do
  source $file
done; unset file

# Make man pages look better with solarized
export LESS_TERMCAP_md=$'\E[0;33m' # begin bold
export LESS_TERMCAP_so=$'\E[1;30;43m' # begin standout-mode - info box
export LESS_TERMCAP_us=$'\E[4;32m' # begin underline
#dummy
